server:
   port: 80
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/language?useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   mybatis:
      typeAliasesPackage: com.zzz.springboot.entity
   pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false
   mail:
      host: smtp.qq.com
      username: 454050427
      password: 18572810802zzz
      properties:
         from: 454050427@qq.com